# Site settings
title: Andrew Milson
url: http://andrewmilson.com
exclude: ['README.md', 'source', 'node_modules', 'package.json', 'Gruntfile.js', '*.command']
markdown: kramdown
permalink: :year/:title/
highlighter: true
